version: 2

references:

terraform_init: &terraform_init
  run:
    name: terraform init
    command: |
      terraform init

jobs:
  build-master:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - run:
          command: |
            docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
            docker build --pull -t "$CI_REGISTRY_IMAGE" .
            docker push "$CI_REGISTRY_IMAGE"
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - *terraform_init
      - run:
          command: |
            docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
            docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
            docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

  validate:
    docker:
        - image: hashicorp/terraform:light
    steps:
        - checkout
        - *terraform_init
        - run:
            name: Terraform validate
            command: cd ./terraform && terraform validate
  plan:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - *terraform_init
      - run:
          name: Terraform plan
          command: cd ./terraform && terraform plan

  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform apply
          command: cd ./terraform && terraform apply -auto-approve

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - build-master:
          filters:
            branches:
              only: master
      - validate
      - plan:
          requires:
              - validate
      - apply:
          type: approval
          requires:
            - plan
            - build-master
          filters:
            branches:
              only: master

