version: 2

references:

terraform_init: &terraform_init
  run:
    name: terraform init
    command: |
      mkdir -p ./creds
      ls ./creds
      echo $GOOGLE_CLOUD_CREDS | base64 -d > ./creds/cloudKeys.json
      ls
      ls ./creds
      cat ./creds/cloudKeys.json
      cd ./terraform
      terraform init

jobs:
  build-master:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - run:
          command: |
            docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
            docker build --pull -t "$CI_REGISTRY_IMAGE" .
            docker push "$CI_REGISTRY_IMAGE"
  build:
    docker:
      - image: docker:dind
    steps:
      - checkout
      - run:
          command: |
            docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
            docker build --pull -t "registry.gitlab.com/chasbob/ricardo-bot:$CIRCLE_BRANCH" .
            docker push "$CI_REGISTRY_IMAGE:$CIRCLE_BRANCH"

  validate:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - *terraform_init
      - run:
          name: Terraform validate
          command: cd ./terraform && terraform validate
  plan:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - *terraform_init
      - run:
          name: Terraform plan
          command: cd ./terraform && terraform plan

  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform apply
          command: cd ./terraform && terraform apply -auto-approve

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - build-master:
          filters:
            branches:
              only: master
      - validate
      - plan:
          requires:
            - validate
      - apply:
          type: approval
          requires:
            - plan
            - build-master
#          filters:
#            branches:
#              only: master

