version: 2

references:

terraform_init: &terraform_init
  run:
    name: terraform init
    command: |
      mkdir -p ./creds
      echo $GOOGLE_CLOUD_CREDS | base64 -d > ./creds/cloudKeys.json
      echo $BOT_AUTH | base64 -d > ./src/auth.json
      cd ./terraform
      terraform init

jobs:
  build-master:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
            docker build --pull -t "${CI_REGISTRY}/${REGISTRY_PATH}" .
            docker push "${CI_REGISTRY}/${REGISTRY_PATH}"
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
            docker build --pull -t "${CI_REGISTRY}/${REGISTRY_PATH}:$CIRCLE_BRANCH" .
            docker push "${CI_REGISTRY}/${REGISTRY_PATH}:$CIRCLE_BRANCH"

  validate:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - *terraform_init
      - run:
          name: Terraform validate
          command: cd ./terraform && terraform validate
  plan:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - *terraform_init
      - run:
          name: Terraform plan
          command: cd ./terraform && TF_VAR_DOCKER_PASSWORD=$CI_REGISTRY_PASSWORD terraform plan

  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - *terraform_init
      - run:
          name: Terraform apply
          command: |
            cd ./terraform
            TF_VAR_DOCKER_PASSWORD=$CI_REGISTRY_PASSWORD terraform destroy -auto-approve
            TF_VAR_DOCKER_PASSWORD=$CI_REGISTRY_PASSWORD terraform apply -auto-approve

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - build-master:
          filters:
            branches:
              only: master
      - validate
      - plan:
          requires:
            - validate
      - apply:
          requires:
            - plan
            - build-master
          filters:
            branches:
              only: master

